<a href="https://colab.research.google.com/github/hongo-daisuke/study-python/blob/master/data_analysis/python_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy

*   多次元かつ大量のベクトルの演算を容易に高速に処理を行うことが出来る



In [ ]:
import numpy as np

### 1次元のnumpy.ndarrayを生成

In [ ]:
# 1次元のnumpy.ndarrayを生成
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

### データへアクセス

In [ ]:
# データへアクセス
a[1]

2

### 2次元のnumpy.ndarrayを生成

In [ ]:
# 2次元のnumpy.ndarrayを生成
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a[0]

array([1, 2, 3])

In [ ]:
a[1][2]

6

### numpy.ndarrayの形状の確認

In [ ]:
# numpy.ndarrayの形状の確認
a.shape

(2, 3)

### numpy.ndarrayが何次元か確認 

In [ ]:
# numpy.ndarrayが何次元か確認
a.ndim

2

### numpy.ndarrayにいくつのデータが存在するか

In [ ]:
# numpy.ndarrayにいくつのデータが存在するか
a.size

6

### 第一引数から第二引数までの1区切りのnumpy.ndarrayを作成

In [ ]:
# 第一引数から第二引数までの1区切りのnumpy.ndarrayを作成
a = np.arange(0, 10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 第一引数から第二引数までの第三引数区切りのnumpy.ndarrayを作成

In [ ]:
# 第一引数から第二引数までの第三引数区切りのnumpy.ndarrayを作成
a = np.arange(0, 20, 5)
a

array([ 0,  5, 10, 15])

### 第一引数 x 第二引数の0の行列を作成

In [ ]:
# 第一引数 x 第二引数の0の行列を作成
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 第一引数 x 第二引数の要素が全て1の行列を作成

In [ ]:
# 第一引数 x 第二引数の要素が全て1の行列を作成
a = np.ones((3, 4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### データが存在しないことを表す欠損値として表す

In [ ]:
# データが存在しないことを表す欠損値として表す
np.nan

nan

### nanの配列を作成

In [ ]:
# nanの配列を作成
[np.nan] * 3

[nan, nan, nan]

### 第一引数から第二引数の間で第三引数分のnumpy.ndarrayを作成

In [ ]:
# 第一引数から第二引数の間で第三引数分のnumpy.ndarrayを作成
np.linspace(0, 3, 5)

array([0.  , 0.75, 1.5 , 2.25, 3.  ])

### .reshape(N, M)で N * Mの形状のnumpy.ndarrayに形を変換

In [ ]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
# .reshape(N, M)で N * Mの形状のnumpy.ndarrayに形を変換
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

### 0~23を2 * 3 * 4の3次元配列に形を変換

In [ ]:
# 0~23を2 * 3 * 4の3次元配列に形を変換
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### 数の多いnumpy.ndarrayの表示方法

In [ ]:
# 数が多いと途中の数値が省略される
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [ ]:
# reshapeしても同様に省略される
np.arange(10000).reshape(100, 100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [ ]:
# set_printoptionsで設定してから表示する
np.set_printoptions(threshold=10000)
np.arange(10000)

### 配列の連結

In [ ]:
# 0から10まで2ステップのnumpy.ndarrayを作成
x = np.arange(0, 10, 2)
x

array([0, 2, 4, 6, 8])

In [ ]:
# 0から5のnumpy.ndarrayを作成
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [ ]:
# 0から100まで20ステップのnumpy.ndarrayを作成
z = np.arange(0, 100, 20)
z

array([ 0, 20, 40, 60, 80])

In [ ]:
# 配列の操作 xにyが追加される
np.append(x, y)

array([0, 2, 4, 6, 8, 0, 1, 2, 3, 4])

In [ ]:
# 配列同士の連結
np.vstack([x, y, z])

array([[ 0,  2,  4,  6,  8],
       [ 0,  1,  2,  3,  4],
       [ 0, 20, 40, 60, 80]])

In [ ]:
# 配列同士の横への連結
np.hstack([x, y, z])

array([ 0,  2,  4,  6,  8,  0,  1,  2,  3,  4,  0, 20, 40, 60, 80])

 ### 配列の計算

In [ ]:
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [ ]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [ ]:
# 配列の引き算
a - b

array([10, 19, 28, 37, 46])

In [ ]:
# 配列の引き算
b - a

array([-10, -19, -28, -37, -46])

In [ ]:
# 掛け算
b * 2

array([0, 2, 4, 6, 8])

In [ ]:
# 掛け算
a * b

array([  0,  20,  60, 120, 200])

## 様々な値の取り出し方

### aの中で30より小さい数値はTrueそれ以外をFalseで表す

In [ ]:
# aの中で30より小さい数値はTrueそれ以外をFalseで表す
a < 30

array([ True,  True, False, False, False])

### np.onesでのnumpy.ndarray作成時のオプション

In [ ]:
# 第2引数にdtype=intと指定することでint型として作成可能
a = np.ones((2, 3), dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1]])

### 代入演算子

In [ ]:
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

### 乱数を生成する。n * mの形状でnumpy.ndarrayを生成

In [ ]:
# 乱数を生成する。n * mの形状でnumpy.ndarrayを生成
a = np.random.random((2, 3))
a

array([[0.16726111, 0.64377285, 0.85984332],
       [0.57082441, 0.62670285, 0.00128284]])

### 配列内の数値を全て足す

In [ ]:
# 配列内の数値を全て足す
a.sum()

2.8696873763607877

### 配列内で一番小さい値を返却

In [ ]:
# 配列内で一番小さい値を返却
a.min()

0.0012828414864946014

### 配列内で一番大きい値を返却

In [ ]:
# 配列内で一番大きい値を返却
a.max()

0.8598433179430357

### 配列内の平均値を返却

In [ ]:
# 配列内の平均値を返却
a.mean()

0.4782812293934646

### axisでどこの方向に計算を行うか指定できる

In [ ]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# axisでどこの方向に計算を行うか指定できる
# 0:縦の列、1:横の行
print(a.sum(axis=0))
print(a.sum(axis=1))

[12 15 18 21]
[ 6 22 38]


### .Tによる転置

In [ ]:
# .Tで転置する
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### resize((N, M))によるサイズの変更

In [ ]:
# resize((N, M)) サイズを変更する
a.resize((2, 6))
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])